[package]
name = "elevator-driver"
version = "0.1.0"
authors = ["Ole Sivert Aarhaug <ole.sivert@aarhaug.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "elevator_driver"
path = "src/lib.rs"

[dependencies]
